### ISSUE TITLE
Revisione repo

### ISSUE THREAD

**Issue by liggiorgio** [CsUnipa/Algoritmi#2]
Sto revisionando completamente il repo, e oltre al solito lavoro di eliminazione duplicati, file non utili (*.exe, temporanei...) e documenti di Compilatori (che sposterò nel repo corrispondente), mi sono imbattuto in alcuni file che preferirei mettere in discussione con voi.
- Sono presenti due PDF con i "pizzini" per la teoria, "Algoritmi + indice Corretto+ Tabellemod 2.pdf" di circa 18 MB e "Domande Algoritmi Definitivo.pdf" grande invece poco meno della metà. I due file mi sembrano uguali, ma immagino che la differenza non stia solo nella dimensione ma anche nel contenuto. Quale dobbiamo tenere?
- Sono presenti due file con prove in itinere del 2008, ma sarei propenso ad eliminarle in quanto obsolete, inoltre il prof non fa più fare esercizi del genere per cui mi sembrano inutili.
Chiedo istruzioni su come agire, la mia intenzione è tenere un solo PDF ed eliminare quelle prove in itinere (tr al'altro, file unici nel loro genere: il resto sono solo esami).

**Comment by liggiorgio** [comment]
UPDATE: ho confrontato pagina per pagina i due pdf e sono identici per contenuto, cambia soltanto l'impaginazione di qualche paragrafo. Propongo di mantenere il file di dimensione minore.

**Comment by alessiolombardo** [comment]
Per quanto riguarda il primo punto sono favorevole al fatto di mantenere solo il pdf più piccolo. Non posso dire nulla sul secondo punto visto che ancora non ho cominciato questa materia.

**Comment by dlion** [comment]
@liggiorgio Quel file compresso è opera mia, il pdf sul telefono può essere utile. *ammicca* :kissing: 
Per il resto fai quello che credi sia meglio xD
